// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheUnraveller.Infrastructure.Data;

#nullable disable

namespace TheUnraveller.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260529113036_AddMissionApprovals")]
    partial class AddMissionApprovals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheUnraveller.Core.Entities.Dialogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MissionId")
                        .HasColumnType("integer");

                    b.Property<int>("NpcId")
                        .HasColumnType("integer");

                    b.Property<string>("NpcResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SuspicionChange")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("NpcId");

                    b.HasIndex("UserId");

                    b.ToTable("Dialogues", (string)null);
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxSuspicion")
                        .HasColumnType("integer");

                    b.Property<int>("NpcId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartSuspicion")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("NpcId");

                    b.ToTable("Missions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalStatus = 0,
                            Description = "Hello! Welcome to your English learning journey. Don't worry if you're not perfect yet — everyone starts somewhere.",
                            Difficulty = "Beginner",
                            Goal = "Practice ordering, small talk, and social English in a café setting.",
                            ImageUrl = "/scenario_coffee.png",
                            Locked = false,
                            MaxSuspicion = 100,
                            NpcId = 1,
                            Stage = "Stage 1",
                            StartSuspicion = 10,
                            Title = "Coffee Shop Conversations",
                            XpReward = 150
                        },
                        new
                        {
                            Id = 2,
                            ApprovalStatus = 0,
                            Description = "You've been assigned several tasks today. Listen carefully to each instruction and complete everything with minimal mistakes.",
                            Difficulty = "Beginner",
                            Goal = "Listen carefully, understand tasks, and execute with precision.",
                            ImageUrl = "/scenario_classroom.png",
                            Locked = false,
                            MaxSuspicion = 100,
                            NpcId = 2,
                            Stage = "Stage 2",
                            StartSuspicion = 10,
                            Title = "Following Instructions",
                            XpReward = 200
                        },
                        new
                        {
                            Id = 3,
                            ApprovalStatus = 0,
                            Description = "Practice arguing your point and reaching agreements in English in a professional context.",
                            Difficulty = "Intermediate",
                            Goal = "Practice arguing your point and reaching agreements in English.",
                            ImageUrl = "",
                            Locked = true,
                            MaxSuspicion = 100,
                            NpcId = 2,
                            Stage = "Stage 3",
                            StartSuspicion = 10,
                            Title = "Debate & Negotiation",
                            XpReward = 300
                        },
                        new
                        {
                            Id = 4,
                            ApprovalStatus = 0,
                            Description = "Ace an English job interview with proper vocabulary and confidence in a professional setting.",
                            Difficulty = "Intermediate",
                            Goal = "Ace an English job interview with proper vocabulary and confidence.",
                            ImageUrl = "",
                            Locked = true,
                            MaxSuspicion = 100,
                            NpcId = 2,
                            Stage = "Stage 4",
                            StartSuspicion = 10,
                            Title = "Job Interview",
                            XpReward = 350
                        },
                        new
                        {
                            Id = 5,
                            ApprovalStatus = 0,
                            Description = "A crime has been committed. As the lead detective, you must gather evidence, interview suspects, and file your report.",
                            Difficulty = "Advanced",
                            Goal = "Describe scenes and solve mysteries in written English.",
                            ImageUrl = "/scenario_detective.png",
                            Locked = false,
                            MaxSuspicion = 100,
                            NpcId = 3,
                            Stage = "Stage 5",
                            StartSuspicion = 10,
                            Title = "Detective Writing",
                            XpReward = 500
                        },
                        new
                        {
                            Id = 6,
                            ApprovalStatus = 0,
                            Description = "Complex multi-character scenarios with layered objectives to test fluency.",
                            Difficulty = "Advanced",
                            Goal = "Complex multi-character scenarios with layered objectives.",
                            ImageUrl = "",
                            Locked = true,
                            MaxSuspicion = 100,
                            NpcId = 3,
                            Stage = "Stage 6",
                            StartSuspicion = 10,
                            Title = "Advanced Roleplay",
                            XpReward = 600
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Npc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NpcEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Npcs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A friendly coffee shop barista in a cyberpunk neon café.",
                            Name = "Barista",
                            NpcEmoji = "☕",
                            Personality = "Polite, helpful, but easily confused by complex orders or suspicious behavior.",
                            Role = "Barista"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A strict operations supervisor monitoring efficiency.",
                            Name = "Supervisor",
                            NpcEmoji = "📋",
                            Personality = "Strict, detail-oriented, expects absolute precision and highly professional English.",
                            Role = "Supervisor"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A veteran inspector analyzing crime evidence.",
                            Name = "Chief Detective",
                            NpcEmoji = "🔍",
                            Personality = "Sharp, cynical, highly analytical, speaks in short, formal detective terms.",
                            Role = "Chief Detective"
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("PaymentUrl")
                        .HasColumnType("text");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriceXp")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ShopItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Reveals hidden clues and hints in dialogues.",
                            Emoji = "🔍",
                            Name = "Detective Magnifier",
                            PriceXp = 200,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Instantly reduces suspicion by 20 points.",
                            Emoji = "✨",
                            Name = "Golden Tongue",
                            PriceXp = 500,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "A rare cosmetic item that fits a master infiltrator.",
                            Emoji = "🧥",
                            Name = "Shadow Cape",
                            PriceXp = 1000,
                            Type = 3
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Features")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Free access to starter missions",
                            DurationDays = 0,
                            Features = new List<string> { "Starter Missions", "Daily Energy" },
                            Name = "Basic",
                            Price = 0m,
                            Tier = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Unlock all features for 30 days",
                            DurationDays = 30,
                            Features = new List<string> { "All Missions", "Unlimited Energy", "Advanced AI feedback" },
                            Name = "Monthly Premium",
                            Price = 49000m,
                            Tier = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Best value for serious learners",
                            DurationDays = 365,
                            Features = new List<string> { "All Missions", "Unlimited Energy", "Priority Support", "Certificate" },
                            Name = "Yearly Premium",
                            Price = 450000m,
                            Tier = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Pay once, access forever",
                            DurationDays = 0,
                            Features = new List<string> { "All Missions", "Unlimited Energy", "Lifetime Updates", "VIP Badge" },
                            Name = "Lifetime Premium",
                            Price = 1200000m,
                            Tier = 3
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Energy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastEnergyRechargedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxEnergy")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("StreakCount")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XpBalance")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "khoapro@gmail.com",
                            Energy = 100,
                            IsPremium = false,
                            LastEnergyRechargedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxEnergy = 100,
                            PasswordHash = "AQAAAAIAAYagAAAAECxHpxxx",
                            Role = 0,
                            StreakCount = 0,
                            Username = "KHOA_PRO",
                            XpBalance = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "minhkhoi@gmail.com",
                            Energy = 100,
                            IsPremium = false,
                            LastEnergyRechargedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxEnergy = 100,
                            PasswordHash = "HASH2",
                            Role = 0,
                            StreakCount = 0,
                            Username = "Minh Khôi",
                            XpBalance = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lananh@gmail.com",
                            Energy = 100,
                            IsPremium = false,
                            LastEnergyRechargedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxEnergy = 100,
                            PasswordHash = "HASH3",
                            Role = 0,
                            StreakCount = 0,
                            Username = "Lan Anh",
                            XpBalance = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tuankhoa@gmail.com",
                            Energy = 100,
                            IsPremium = false,
                            LastEnergyRechargedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxEnergy = 100,
                            PasswordHash = "HASH4",
                            Role = 0,
                            StreakCount = 0,
                            Username = "Tuấn Khoa",
                            XpBalance = 0
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique();

                    b.ToTable("UserInventories", (string)null);
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentSuspicion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MissionId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TurnCount")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("UserId", "MissionId")
                        .IsUnique();

                    b.ToTable("UserProgresses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10,
                            CurrentSuspicion = 15,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 1,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 2,
                            XpEarned = 1000
                        },
                        new
                        {
                            Id = 11,
                            CurrentSuspicion = 20,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 2,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 2,
                            XpEarned = 1200
                        },
                        new
                        {
                            Id = 12,
                            CurrentSuspicion = 25,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 3,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 2,
                            XpEarned = 1300
                        },
                        new
                        {
                            Id = 13,
                            CurrentSuspicion = 30,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 4,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 2,
                            XpEarned = 1300
                        },
                        new
                        {
                            Id = 20,
                            CurrentSuspicion = 10,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 1,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 3,
                            XpEarned = 950
                        },
                        new
                        {
                            Id = 21,
                            CurrentSuspicion = 15,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 2,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 3,
                            XpEarned = 1000
                        },
                        new
                        {
                            Id = 22,
                            CurrentSuspicion = 20,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 3,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 3,
                            XpEarned = 1000
                        },
                        new
                        {
                            Id = 23,
                            CurrentSuspicion = 25,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 4,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 3,
                            XpEarned = 1000
                        },
                        new
                        {
                            Id = 30,
                            CurrentSuspicion = 20,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 1,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 4,
                            XpEarned = 800
                        },
                        new
                        {
                            Id = 31,
                            CurrentSuspicion = 22,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 2,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 4,
                            XpEarned = 800
                        },
                        new
                        {
                            Id = 32,
                            CurrentSuspicion = 25,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 3,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 4,
                            XpEarned = 800
                        },
                        new
                        {
                            Id = 33,
                            CurrentSuspicion = 28,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 4,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 4,
                            XpEarned = 800
                        },
                        new
                        {
                            Id = 40,
                            CurrentSuspicion = 30,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 1,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 1,
                            XpEarned = 600
                        },
                        new
                        {
                            Id = 41,
                            CurrentSuspicion = 35,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 2,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 1,
                            XpEarned = 650
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Dialogue", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheUnraveller.Core.Entities.Npc", "Npc")
                        .WithMany()
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheUnraveller.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Npc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Mission", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheUnraveller.Core.Entities.Npc", "Npc")
                        .WithMany()
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Payment", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserInventory", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.ShopItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheUnraveller.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserProgress", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheUnraveller.Core.Entities.User", "User")
                        .WithMany("Progresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.User", b =>
                {
                    b.Navigation("Progresses");
                });
#pragma warning restore 612, 618
        }
    }
}
