// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheUnraveller.Infrastructure.Data;

#nullable disable

namespace TheUnraveller.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608041618_UpdateMissionImages")]
    partial class UpdateMissionImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheUnraveller.Core.Entities.Dialogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MissionId")
                        .HasColumnType("integer");

                    b.Property<int>("NpcId")
                        .HasColumnType("integer");

                    b.Property<string>("NpcResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SuspicionChange")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("NpcId");

                    b.HasIndex("UserId");

                    b.ToTable("Dialogues", (string)null);
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrammarTarget")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxSuspicion")
                        .HasColumnType("integer");

                    b.Property<int>("NpcId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartSuspicion")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("NpcId");

                    b.ToTable("Missions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalStatus = 0,
                            Description = "*The hum of neon lights fills the cozy cyber-café. The Barista wipes down the metallic counter, looking up with a friendly smile.* \"Welcome to Neon Mug! What can I get started for you today? We've got fresh cyber-brews and synthetic pastries.\"",
                            Difficulty = "Beginner",
                            Goal = "Luyện tập gọi món, trò chuyện ngắn và tiếng Anh giao tiếp trong quán cà phê.",
                            GrammarTarget = "Sử dụng câu nói lịch sự với 'Would like' hoặc động từ khuyết thiếu 'Could/May'.",
                            ImageUrl = "/scenario_coffee.png",
                            Locked = false,
                            MaxSuspicion = 100,
                            NpcId = 1,
                            Stage = "Stage 1",
                            StartSuspicion = 10,
                            Title = "Giao tiếp tại Quán Cà phê",
                            XpReward = 150
                        },
                        new
                        {
                            Id = 2,
                            ApprovalStatus = 0,
                            Description = "*The Supervisor taps their digital clipboard impatiently as you step into the assembly bay. The neon screens flicker behind them.* \"You're late. We have a heavy shipment of hover-car battery cores to calibrate today. Let me know when you're ready for your instructions.\"",
                            Difficulty = "Beginner",
                            Goal = "Lắng nghe cẩn thận, hiểu nhiệm vụ và thực hiện với độ chính xác cao.",
                            GrammarTarget = "Sử dụng câu mệnh lệnh (Imperatives) hoặc thể bị động (Passive voice) để xác nhận nhiệm vụ.",
                            ImageUrl = "/scenario_classroom.png",
                            Locked = true,
                            MaxSuspicion = 100,
                            NpcId = 2,
                            Stage = "Stage 2",
                            StartSuspicion = 10,
                            Title = "Làm theo Chỉ dẫn",
                            XpReward = 200
                        },
                        new
                        {
                            Id = 3,
                            ApprovalStatus = 0,
                            Description = "*The glass walls of the boardroom overlook the sprawling city skyline. The CEO leans forward, folding their hands.* \"Thank you for coming. We need to reach a deal on the technology sharing agreement. If you agree to our terms, we can sign today. What are your thoughts?\"",
                            Difficulty = "Intermediate",
                            Goal = "Luyện tập bảo vệ quan điểm và đạt được thỏa thuận bằng tiếng Anh.",
                            GrammarTarget = "Sử dụng câu điều kiện loại 1 (If... will...) hoặc loại 2 (If... would...) để đàm phán.",
                            ImageUrl = "/scenario_boardroom.png",
                            Locked = true,
                            MaxSuspicion = 100,
                            NpcId = 2,
                            Stage = "Stage 3",
                            StartSuspicion = 10,
                            Title = "Tranh luận & Đàm phán",
                            XpReward = 300
                        },
                        new
                        {
                            Id = 4,
                            ApprovalStatus = 0,
                            Description = "*You sit opposite the interviewer in a sleek high-tech office. The HR manager smiles warmly.* \"Welcome. I've reviewed your credentials and they look impressive. To begin, could you tell me why you want to work here at CyberTech Industries?\"",
                            Difficulty = "Intermediate",
                            Goal = "Vượt qua buổi phỏng vấn xin việc bằng tiếng Anh với vốn từ vựng chuyên nghiệp và tự tin.",
                            GrammarTarget = "Sử dụng câu phức chứa mệnh đề quan hệ (Relative Clauses) hoặc liên từ (Because, Although).",
                            ImageUrl = "/scenario_interview.png",
                            Locked = true,
                            MaxSuspicion = 100,
                            NpcId = 2,
                            Stage = "Stage 4",
                            StartSuspicion = 10,
                            Title = "Phỏng vấn Xin việc",
                            XpReward = 350
                        },
                        new
                        {
                            Id = 5,
                            ApprovalStatus = 0,
                            Description = "*Rain beats against the dirty precinct window. Chief Detective Henderson tosses a case file containing glowing holograms onto the table.* \"Grab a seat. The cyber-vault at Sector 7 was cracked wide open last night. Tell me exactly what you found at the crime scene.\"",
                            Difficulty = "Advanced",
                            Goal = "Mô tả hiện trường vụ án và phá giải các bí ẩn bằng văn bản tiếng Anh.",
                            GrammarTarget = "Sử dụng trạng từ mô tả (Descriptive Adverbs) và thì Quá khứ đơn (Past Simple) để báo cáo chứng cứ.",
                            ImageUrl = "/scenario_detective.png",
                            Locked = true,
                            MaxSuspicion = 100,
                            NpcId = 3,
                            Stage = "Stage 5",
                            StartSuspicion = 10,
                            Title = "Báo cáo Điều tra",
                            XpReward = 500
                        },
                        new
                        {
                            Id = 6,
                            ApprovalStatus = 0,
                            Description = "*You stand in the dim undercity market, surrounded by holographic advertisements. A shady merchant whispers from the shadows.* \"Psst... I hear you're looking for the decryption key. I might have it, but it's going to cost you. What did you bring to trade?\"",
                            Difficulty = "Advanced",
                            Goal = "Xử lý các tình huống phức tạp có nhiều nhân vật với mục tiêu đa lớp.",
                            GrammarTarget = "Sử dụng câu giả định (Subjunctive Mood) hoặc lối nói gián tiếp (Reported Speech) ở trình độ cao.",
                            ImageUrl = "/scenario_undercity.png",
                            Locked = true,
                            MaxSuspicion = 100,
                            NpcId = 3,
                            Stage = "Stage 6",
                            StartSuspicion = 10,
                            Title = "Nhập vai Nâng cao",
                            XpReward = 600
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Npc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NpcEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Npcs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Một nhân viên pha chế thân thiện trong quán cà phê cyberpunk neon rực rỡ.",
                            Name = "Barista",
                            NpcEmoji = "☕",
                            Personality = "Lịch sự, chu đáo, nhưng dễ bị bối rối trước các yêu cầu phức tạp hoặc hành vi đáng ngờ.",
                            Role = "Pha chế"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Giám sát viên vận hành nghiêm khắc kiểm soát hiệu suất làm việc.",
                            Name = "Supervisor",
                            NpcEmoji = "📋",
                            Personality = "Nghiêm khắc, chú trọng chi tiết, đòi hỏi sự chính xác tuyệt đối và tiếng Anh chuyên nghiệp cao.",
                            Role = "Giám sát viên"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Thanh tra kỳ cựu đang phân tích bằng chứng tội phạm.",
                            Name = "Chief Detective",
                            NpcEmoji = "🔍",
                            Personality = "Sắc sảo, hoài nghi, tính phân tích cao, giao tiếp bằng các thuật ngữ thám tử ngắn gọn, trang trọng.",
                            Role = "Thám tử Trưởng"
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("PaymentUrl")
                        .HasColumnType("text");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriceXp")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ShopItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tiết lộ các manh mối và gợi ý ẩn trong các đoạn hội thoại.",
                            Emoji = "🔍",
                            Name = "Kính Lúp Thám Tử",
                            PriceXp = 200,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Giảm ngay lập tức 20 điểm nghi ngờ từ phía NPC.",
                            Emoji = "✨",
                            Name = "Khéo Ăn Khéo Nói",
                            PriceXp = 500,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vật phẩm trang trí hiếm có phù hợp cho một điệp viên xâm nhập bậc thầy.",
                            Emoji = "🧥",
                            Name = "Áo Choàng Bóng Đêm",
                            PriceXp = 1000,
                            Type = 3
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Features")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quyền truy cập miễn phí giới hạn vào các kịch bản bắt đầu",
                            DurationDays = 0,
                            Features = new List<string> { "Kịch bản khởi đầu", "Năng lượng mỗi ngày" },
                            Name = "Gói Miễn Phí",
                            Price = 0m,
                            Tier = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mở khóa toàn bộ tính năng và kịch bản cao cấp",
                            DurationDays = 30,
                            Features = new List<string> { "Toàn bộ Kịch bản", "Năng lượng vô cực", "Phản hồi AI nâng cao" },
                            Name = "Premium VIP",
                            Price = 199000m,
                            Tier = 1
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Energy")
                        .HasColumnType("integer");

                    b.Property<string>("EnglishLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastEnergyRechargedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxEnergy")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("StreakCount")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XpBalance")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "khoapro@gmail.com",
                            Energy = 100,
                            EnglishLevel = "B1",
                            IsPremium = false,
                            LastEnergyRechargedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxEnergy = 100,
                            PasswordHash = "AQAAAAIAAYagAAAAENK5j34f8aH1J11qK7bV5P9mH0Vn0E9G5tWp2e/o9v8u9p8n8=",
                            Role = 0,
                            StreakCount = 0,
                            Username = "KHOA_PRO",
                            XpBalance = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "minhkhoi@gmail.com",
                            Energy = 100,
                            EnglishLevel = "B1",
                            IsPremium = false,
                            LastEnergyRechargedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxEnergy = 100,
                            PasswordHash = "AQAAAAIAAYagAAAAENK5j34f8aH1J11qK7bV5P9mH0Vn0E9G5tWp2e/o9v8u9p8n8=",
                            Role = 0,
                            StreakCount = 0,
                            Username = "Minh Khôi",
                            XpBalance = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lananh@gmail.com",
                            Energy = 100,
                            EnglishLevel = "B1",
                            IsPremium = false,
                            LastEnergyRechargedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxEnergy = 100,
                            PasswordHash = "AQAAAAIAAYagAAAAENK5j34f8aH1J11qK7bV5P9mH0Vn0E9G5tWp2e/o9v8u9p8n8=",
                            Role = 0,
                            StreakCount = 0,
                            Username = "Lan Anh",
                            XpBalance = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tuankhoa@gmail.com",
                            Energy = 100,
                            EnglishLevel = "B1",
                            IsPremium = false,
                            LastEnergyRechargedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxEnergy = 100,
                            PasswordHash = "AQAAAAIAAYagAAAAENK5j34f8aH1J11qK7bV5P9mH0Vn0E9G5tWp2e/o9v8u9p8n8=",
                            Role = 0,
                            StreakCount = 0,
                            Username = "Tuấn Khoa",
                            XpBalance = 0
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique();

                    b.ToTable("UserInventories", (string)null);
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CompletionToken")
                        .HasColumnType("text");

                    b.Property<int>("CurrentSuspicion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MissionId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TurnCount")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("UserId", "MissionId")
                        .IsUnique();

                    b.ToTable("UserProgresses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10,
                            CompletedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletionToken = "UNRV-SEED-2-1",
                            CurrentSuspicion = 15,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 1,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 2,
                            XpEarned = 1000
                        },
                        new
                        {
                            Id = 11,
                            CompletedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletionToken = "UNRV-SEED-2-2",
                            CurrentSuspicion = 20,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 2,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 2,
                            XpEarned = 1200
                        },
                        new
                        {
                            Id = 12,
                            CompletedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletionToken = "UNRV-SEED-2-3",
                            CurrentSuspicion = 25,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 3,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 2,
                            XpEarned = 1300
                        },
                        new
                        {
                            Id = 13,
                            CompletedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletionToken = "UNRV-SEED-2-4",
                            CurrentSuspicion = 30,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 4,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 2,
                            XpEarned = 1300
                        },
                        new
                        {
                            Id = 20,
                            CompletedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletionToken = "UNRV-SEED-3-1",
                            CurrentSuspicion = 10,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 1,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 3,
                            XpEarned = 950
                        },
                        new
                        {
                            Id = 21,
                            CompletedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletionToken = "UNRV-SEED-3-2",
                            CurrentSuspicion = 15,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 2,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 3,
                            XpEarned = 1000
                        },
                        new
                        {
                            Id = 22,
                            CompletedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletionToken = "UNRV-SEED-3-3",
                            CurrentSuspicion = 20,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 3,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 3,
                            XpEarned = 1000
                        },
                        new
                        {
                            Id = 23,
                            CompletedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletionToken = "UNRV-SEED-3-4",
                            CurrentSuspicion = 25,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 4,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 3,
                            XpEarned = 1000
                        },
                        new
                        {
                            Id = 30,
                            CompletedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletionToken = "UNRV-SEED-4-1",
                            CurrentSuspicion = 20,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 1,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 4,
                            XpEarned = 800
                        },
                        new
                        {
                            Id = 31,
                            CompletedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletionToken = "UNRV-SEED-4-2",
                            CurrentSuspicion = 22,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 2,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 4,
                            XpEarned = 800
                        },
                        new
                        {
                            Id = 32,
                            CompletedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletionToken = "UNRV-SEED-4-3",
                            CurrentSuspicion = 25,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 3,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 4,
                            XpEarned = 800
                        },
                        new
                        {
                            Id = 33,
                            CompletedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletionToken = "UNRV-SEED-4-4",
                            CurrentSuspicion = 28,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 4,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 4,
                            XpEarned = 800
                        },
                        new
                        {
                            Id = 40,
                            CompletedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletionToken = "UNRV-SEED-1-1",
                            CurrentSuspicion = 30,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 1,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 1,
                            XpEarned = 600
                        },
                        new
                        {
                            Id = 41,
                            CompletedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CompletionToken = "UNRV-SEED-1-2",
                            CurrentSuspicion = 35,
                            LastActivity = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MissionId = 2,
                            Status = 1,
                            TurnCount = 5,
                            UserId = 1,
                            XpEarned = 650
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Dialogue", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheUnraveller.Core.Entities.Npc", "Npc")
                        .WithMany()
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheUnraveller.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Npc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Mission", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheUnraveller.Core.Entities.Npc", "Npc")
                        .WithMany()
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Payment", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserInventory", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.ShopItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheUnraveller.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserProgress", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheUnraveller.Core.Entities.User", "User")
                        .WithMany("Progresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.User", b =>
                {
                    b.Navigation("Progresses");
                });
#pragma warning restore 612, 618
        }
    }
}
