// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheUnraveller.Infrastructure.Data;

#nullable disable

namespace TheUnraveller.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620165807_UpdateMissionChoices")]
    partial class UpdateMissionChoices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheUnraveller.Core.Entities.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CriteriaType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("MinAverageScore")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RequiredCount")
                        .HasColumnType("integer");

                    b.Property<int?>("SkillAxis")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Badges", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriteriaType = "FirstCompletion",
                            Description = "Complete your first mission",
                            Icon = "👣",
                            Name = "First Steps"
                        },
                        new
                        {
                            Id = 2,
                            CriteriaType = "MinAverageScore",
                            Description = "Achieve an average score of 70 or higher on any mission",
                            Icon = "🎯",
                            MinAverageScore = 70,
                            Name = "Skillful"
                        },
                        new
                        {
                            Id = 3,
                            CriteriaType = "MinAverageScore",
                            Description = "Achieve an average score of 90 or higher on any mission",
                            Icon = "💎",
                            MinAverageScore = 90,
                            Name = "Perfectionist"
                        },
                        new
                        {
                            Id = 4,
                            CriteriaType = "Streak",
                            Description = "Complete 5 missions in a row without failing",
                            Icon = "🔥",
                            Name = "Streak Master",
                            RequiredCount = 5
                        },
                        new
                        {
                            Id = 5,
                            CriteriaType = "TotalXp",
                            Description = "Earn 1000 total XP",
                            Icon = "🏆",
                            Name = "Writing Coach",
                            RequiredCount = 1000
                        },
                        new
                        {
                            Id = 6,
                            CriteriaType = "PerfectTurn",
                            Description = "Receive all scores above 80 in a single turn",
                            Icon = "✨",
                            Name = "Polished"
                        },
                        new
                        {
                            Id = 7,
                            CriteriaType = "DomainDiversity",
                            Description = "Complete missions in all three domains: Professional, Academic, Social",
                            Icon = "🌍",
                            Name = "Linguist"
                        },
                        new
                        {
                            Id = 8,
                            CriteriaType = "TotalCompletions",
                            Description = "Complete 10 missions total",
                            Icon = "📚",
                            Name = "Lifetime Learner",
                            RequiredCount = 10
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Correction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Axis")
                        .HasColumnType("integer");

                    b.Property<string>("CorrectedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DialogueId")
                        .HasColumnType("integer");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Axis");

                    b.HasIndex("DialogueId");

                    b.ToTable("Corrections", (string)null);
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Dialogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClarityScore")
                        .HasColumnType("integer");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GrammarScore")
                        .HasColumnType("integer");

                    b.Property<int>("MissionId")
                        .HasColumnType("integer");

                    b.Property<int?>("NaturalnessScore")
                        .HasColumnType("integer");

                    b.Property<int>("NpcId")
                        .HasColumnType("integer");

                    b.Property<string>("NpcResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StructureScore")
                        .HasColumnType("integer");

                    b.Property<int>("SuspicionChange")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ToneScore")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("VocabularyScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("NpcId");

                    b.HasIndex("UserId");

                    b.ToTable("Dialogues", (string)null);
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<int>("CefrLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Domain")
                        .HasColumnType("integer");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrammarTarget")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("InitialChoices")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxSuspicion")
                        .HasColumnType("integer");

                    b.Property<int>("MinAverageScore")
                        .HasColumnType("integer");

                    b.Property<int>("MinTurnsToComplete")
                        .HasColumnType("integer");

                    b.Property<int>("NpcId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartSuspicion")
                        .HasColumnType("integer");

                    b.Property<string>("SyntaxPuzzlesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WritingObjective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XpReward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("NpcId");

                    b.ToTable("Missions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalStatus = 0,
                            CefrLevel = 1,
                            Description = "*The warm aroma of freshly ground coffee fills the cozy café. The Barista wipes down the wooden counter and looks up with a friendly smile.* \"Welcome to Coffee Corner! What can I get started for you today? We've got fresh house blends and hot pastries.\"",
                            Difficulty = "Beginner",
                            Domain = 0,
                            Goal = "Luyện tập gọi món, trò chuyện ngắn và tiếng Anh giao tiếp trong quán cà phê.",
                            GrammarTarget = "Sử dụng câu nói lịch sự với 'Would like' hoặc động từ khuyết thiếu 'Could/May'.",
                            ImageUrl = "/scenario_coffee.png",
                            InitialChoices = new List<string> { "I would like to order a cup of coffee, please.", "Could I see the menu, please?", "Do you recommend any house blends today?", "What kind of hot pastries do you have?" },
                            Locked = false,
                            MaxSuspicion = 100,
                            MinAverageScore = 60,
                            MinTurnsToComplete = 5,
                            NpcId = 1,
                            Stage = "Stage 1",
                            StartSuspicion = 10,
                            SyntaxPuzzlesJson = "[]",
                            Title = "Giao tiếp tại Quán Cà phê",
                            WritingObjective = "Sử dụng câu nói lịch sự với 'Would like' hoặc động từ khuyết thiếu 'Could/May'.",
                            XpReward = 150
                        },
                        new
                        {
                            Id = 2,
                            ApprovalStatus = 0,
                            CefrLevel = 2,
                            Description = "*The Supervisor reviews their clipboard as you step into the stockroom.* \"Glad you're here. We have a large shipment of office equipment to sort and organize today. Let me know when you're ready for your instructions.\"",
                            Difficulty = "Beginner",
                            Domain = 0,
                            Goal = "Lắng nghe cẩn thận, hiểu nhiệm vụ và thực hiện với độ chính xác cao.",
                            GrammarTarget = "Sử dụng câu mệnh lệnh (Imperatives) hoặc thể bị động (Passive voice) để xác nhận nhiệm vụ.",
                            ImageUrl = "/scenario_classroom.png",
                            InitialChoices = new List<string> { "Understood. What is the first task I need to do?", "I'm ready. Please give me the instructions.", "Can you guide me on what to do first?", "I will do my best to follow the guidelines." },
                            Locked = true,
                            MaxSuspicion = 100,
                            MinAverageScore = 65,
                            MinTurnsToComplete = 5,
                            NpcId = 2,
                            Stage = "Stage 2",
                            StartSuspicion = 10,
                            SyntaxPuzzlesJson = "[]",
                            Title = "Làm theo Chỉ dẫn",
                            WritingObjective = "Sử dụng câu mệnh lệnh (Imperatives) hoặc thể bị động (Passive voice) để xác nhận nhiệm vụ.",
                            XpReward = 200
                        },
                        new
                        {
                            Id = 3,
                            ApprovalStatus = 0,
                            CefrLevel = 3,
                            Description = "*The glass walls of the boardroom overlook the city skyline. The CEO leans forward, folding their hands.* \"Thank you for coming. We need to reach a deal on the technology sharing agreement. If you agree to our terms, we can sign today. What are your thoughts?\"",
                            Difficulty = "Intermediate",
                            Domain = 0,
                            Goal = "Luyện tập bảo vệ quan điểm và đạt được thỏa thuận bằng tiếng Anh.",
                            GrammarTarget = "Sử dụng câu điều kiện loại 1 (If... will...) hoặc loại 2 (If... would...) để đàm phán.",
                            ImageUrl = "/scenario_boardroom.png",
                            InitialChoices = new List<string> { "I'm ready. Let's start the negotiation.", "Can you explain the main points of the agreement?", "I'd like to discuss the terms of this deal.", "Let's look at the topic from both sides." },
                            Locked = true,
                            MaxSuspicion = 100,
                            MinAverageScore = 70,
                            MinTurnsToComplete = 5,
                            NpcId = 2,
                            Stage = "Stage 3",
                            StartSuspicion = 10,
                            SyntaxPuzzlesJson = "[]",
                            Title = "Tranh luận & Đàm phán",
                            WritingObjective = "Sử dụng câu điều kiện loại 1 (If... will...) hoặc loại 2 (If... would...) để đàm phán.",
                            XpReward = 300
                        },
                        new
                        {
                            Id = 4,
                            ApprovalStatus = 0,
                            CefrLevel = 3,
                            Description = "*You sit opposite the interviewer in a professional corporate office. The HR manager smiles warmly.* \"Welcome. I've reviewed your resume, and it's quite impressive. To begin, could you tell me why you want to work at our company?\"",
                            Difficulty = "Intermediate",
                            Domain = 0,
                            Goal = "Vượt qua buổi phỏng vấn xin việc bằng tiếng Anh với vốn từ vựng chuyên nghiệp và tự tin.",
                            GrammarTarget = "Sử dụng câu phức chứa mệnh đề quan hệ (Relative Clauses) hoặc liên từ (Because, Although).",
                            ImageUrl = "/scenario_interview.png",
                            InitialChoices = new List<string> { "Good morning. Thank you for having me today.", "I'm excited to share my experience with you.", "I'm ready for the interview questions.", "Thank you. I'm glad to have this opportunity." },
                            Locked = true,
                            MaxSuspicion = 100,
                            MinAverageScore = 75,
                            MinTurnsToComplete = 6,
                            NpcId = 2,
                            Stage = "Stage 4",
                            StartSuspicion = 10,
                            SyntaxPuzzlesJson = "[]",
                            Title = "Phỏng vấn Xin việc",
                            WritingObjective = "Sử dụng câu phức chứa mệnh đề quan hệ (Relative Clauses) hoặc liên từ (Because, Although).",
                            XpReward = 350
                        },
                        new
                        {
                            Id = 5,
                            ApprovalStatus = 0,
                            CefrLevel = 4,
                            Description = "*The Director sits at their desk, looking concerned.* \"Welcome, please have a seat. I heard there was an unexpected issue with our client database yesterday. Can you tell me exactly what happened and what steps were taken to resolve it?\"",
                            Difficulty = "Advanced",
                            Domain = 0,
                            Goal = "Mô tả sự cố xảy ra tại nơi làm việc và đề xuất hướng giải quyết bằng tiếng Anh.",
                            GrammarTarget = "Sử dụng trạng từ mô tả (Descriptive Adverbs) và thì Quá khứ đơn (Past Simple) để báo cáo chứng cứ.",
                            ImageUrl = "/scenario_detective.png",
                            InitialChoices = new List<string> { "I'm on the case. What details do we have?", "Let's start by examining the evidence.", "Where was the victim last seen?", "I'll solve this. What's our first clue." },
                            Locked = true,
                            MaxSuspicion = 100,
                            MinAverageScore = 80,
                            MinTurnsToComplete = 6,
                            NpcId = 3,
                            Stage = "Stage 5",
                            StartSuspicion = 10,
                            SyntaxPuzzlesJson = "[]",
                            Title = "Báo cáo Sự cố Công việc",
                            WritingObjective = "Sử dụng trạng từ mô tả (Descriptive Adverbs) và thì Quá khứ đơn (Past Simple) để báo cáo chứng cứ.",
                            XpReward = 500
                        },
                        new
                        {
                            Id = 6,
                            ApprovalStatus = 0,
                            CefrLevel = 5,
                            Description = "*You stand in the modern office of a wholesale supplier. The sales representative crosses their arms and smiles.* \"Thanks for coming in. I understand you'd like to place a large order for your manufacturing line. We can discuss volume discounts. What terms did you have in mind?\"",
                            Difficulty = "Advanced",
                            Domain = 2,
                            Goal = "Thương lượng giá cả và các điều khoản giao hàng với nhà cung cấp nguyên liệu.",
                            GrammarTarget = "Sử dụng câu giả định (Subjunctive Mood) hoặc lối nói gián tiếp (Reported Speech) ở trình độ cao.",
                            ImageUrl = "/scenario_undercity.png",
                            InitialChoices = new List<string> { "Hello!", "Can you help me?", "I have a question.", "Let's start." },
                            Locked = true,
                            MaxSuspicion = 100,
                            MinAverageScore = 85,
                            MinTurnsToComplete = 7,
                            NpcId = 3,
                            Stage = "Stage 6",
                            StartSuspicion = 10,
                            SyntaxPuzzlesJson = "[]",
                            Title = "Đàm phán với Nhà cung cấp",
                            WritingObjective = "Sử dụng câu giả định (Subjunctive Mood) hoặc lối nói gián tiếp (Reported Speech) ở trình độ cao.",
                            XpReward = 600
                        },
                        new
                        {
                            Id = 7,
                            ApprovalStatus = 0,
                            CefrLevel = 2,
                            Description = "*Your supervisor hands you a notes sheet.* \"We need to schedule a team meeting about the Q3 project targets. Draft the invitation email to all department heads. Make it professional but urgent.\"",
                            Difficulty = "Intermediate",
                            Domain = 1,
                            Goal = "Tạo email chuyên nghiệp với cấu trúc rõ ràng và ngôn ngữ phù hợp.",
                            GrammarTarget = "Sử dụng câu bị động (Passive Voice) và từ nối (Furthermore, However) trong văn bản hành chính.",
                            ImageUrl = "/scenario_classroom.png",
                            InitialChoices = new List<string> { "Hello!", "Can you help me?", "I have a question.", "Let's start." },
                            Locked = true,
                            MaxSuspicion = 100,
                            MinAverageScore = 65,
                            MinTurnsToComplete = 5,
                            NpcId = 2,
                            Stage = "Stage 7",
                            StartSuspicion = 10,
                            SyntaxPuzzlesJson = "[]",
                            Title = "Viết Email Công việc",
                            WritingObjective = "Sử dụng câu bị động (Passive Voice) và từ nối (Furthermore, However) trong văn bản hành chính.",
                            XpReward = 280
                        },
                        new
                        {
                            Id = 8,
                            ApprovalStatus = 0,
                            CefrLevel = 3,
                            Description = "*The conference room is full of investors. The product manager nods at you.* \"We're counting on you to pitch the new software platform. Remember: features, benefits, market potential. Make it compelling.\"",
                            Difficulty = "Advanced",
                            Domain = 0,
                            Goal = "Giới thiệu sản phẩm mới bằng tiếng Anh với cấu trúc logic và từ vựng phong phú.",
                            GrammarTarget = "Sử dụng thì tương lai đơn (Future Simple) và câu so sánh hơn (Comparative forms) để mô tả ưu điểm.",
                            ImageUrl = "/scenario_boardroom.png",
                            InitialChoices = new List<string> { "Hello!", "Can you help me?", "I have a question.", "Let's start." },
                            Locked = true,
                            MaxSuspicion = 100,
                            MinAverageScore = 70,
                            MinTurnsToComplete = 6,
                            NpcId = 2,
                            Stage = "Stage 8",
                            StartSuspicion = 10,
                            SyntaxPuzzlesJson = "[]",
                            Title = "Thuyết trình Sản phẩm",
                            WritingObjective = "Sử dụng thì tương lai đơn (Future Simple) và câu so sánh hơn (Comparative forms) để mô tả ưu điểm.",
                            XpReward = 400
                        },
                        new
                        {
                            Id = 9,
                            ApprovalStatus = 0,
                            CefrLevel = 4,
                            Description = "*Across the polished table, the potential partner taps the draft agreement.* \"We can offer exclusive distribution rights, but your margin demands are steep. Let's find a middle ground that works for both companies.\"",
                            Difficulty = "Advanced",
                            Domain = 0,
                            Goal = "Thương lượng các điều khoản hợp đồng và tìm điểm chung.",
                            GrammarTarget = "Sử dụng câu điều kiện loại 2 (If I were...) và từ trung lập (Compromise, Concession) trong đàm phán.",
                            ImageUrl = "/scenario_boardroom.png",
                            InitialChoices = new List<string> { "Hello!", "Can you help me?", "I have a question.", "Let's start." },
                            Locked = true,
                            MaxSuspicion = 100,
                            MinAverageScore = 75,
                            MinTurnsToComplete = 6,
                            NpcId = 2,
                            Stage = "Stage 9",
                            StartSuspicion = 10,
                            SyntaxPuzzlesJson = "[]",
                            Title = "Đàm phán Hợp đồng",
                            WritingObjective = "Sử dụng câu điều kiện loại 2 (If I were...) và từ trung lập (Compromise, Concession) trong đàm phán.",
                            XpReward = 450
                        },
                        new
                        {
                            Id = 10,
                            ApprovalStatus = 0,
                            CefrLevel = 1,
                            Description = "*You find yourself at a rooftop reception overlooking the evening skyline. A friendly attendee approaches you.* \"Hi there! What brings you to this event? I don't think we've met before.\"",
                            Difficulty = "Beginner",
                            Domain = 2,
                            Goal = "Tham gia cuộc trò chuyện thân thiện với từ ngữ tự nhiên và phong cách lịch sự.",
                            GrammarTarget = "Sử dụng thì quá khứ đơn (Past Simple) để kể chuyện và câu hỏi mở (What about you?).",
                            ImageUrl = "/scenario_coffee.png",
                            InitialChoices = new List<string> { "Hello!", "Can you help me?", "I have a question.", "Let's start." },
                            Locked = true,
                            MaxSuspicion = 100,
                            MinAverageScore = 55,
                            MinTurnsToComplete = 5,
                            NpcId = 3,
                            Stage = "Stage 10",
                            StartSuspicion = 10,
                            SyntaxPuzzlesJson = "[]",
                            Title = "Trò chuyện Xã giao",
                            WritingObjective = "Sử dụng thì quá khứ đơn (Past Simple) để kể chuyện và câu hỏi mở (What about you?).",
                            XpReward = 180
                        },
                        new
                        {
                            Id = 11,
                            ApprovalStatus = 0,
                            CefrLevel = 4,
                            Description = "*The seminar room is filled with researchers. The professor clears their throat.* \"Today's topic: the social impact of automation. I'd like to hear your perspective on the shift in labor markets.\"",
                            Difficulty = "Advanced",
                            Domain = 1,
                            Goal = "Tham gia thảo luận học thuật với lập luận có cấu trúc và từ nối học thuật.",
                            GrammarTarget = "Sử dụng mệnh đề tương quan (Relative Clauses) và từ nối học thuật (Therefore, Consequently).",
                            ImageUrl = "/scenario_classroom.png",
                            InitialChoices = new List<string> { "Hello!", "Can you help me?", "I have a question.", "Let's start." },
                            Locked = true,
                            MaxSuspicion = 100,
                            MinAverageScore = 75,
                            MinTurnsToComplete = 6,
                            NpcId = 2,
                            Stage = "Stage 11",
                            StartSuspicion = 10,
                            SyntaxPuzzlesJson = "[]",
                            Title = "Thảo luận Học thuật",
                            WritingObjective = "Sử dụng mệnh đề tương quan (Relative Clauses) và từ nối học thuật (Therefore, Consequently).",
                            XpReward = 420
                        },
                        new
                        {
                            Id = 12,
                            ApprovalStatus = 0,
                            CefrLevel = 2,
                            Description = "*The customer service portal flashes a notification. An unhappy customer's message appears on the screen:* \"My order was supposed to arrive yesterday! This is unacceptable!\" *You type your response.*",
                            Difficulty = "Intermediate",
                            Domain = 0,
                            Goal = "Giải quyết phàn nàn của khách hàng với thái độ tích cực và giải pháp hiệu quả.",
                            GrammarTarget = "Sử dụng câu bị động (Passive Voice) và lời xin lỗi lịch sự (I apologize for...).",
                            ImageUrl = "/scenario_classroom.png",
                            InitialChoices = new List<string> { "Hello!", "Can you help me?", "I have a question.", "Let's start." },
                            Locked = true,
                            MaxSuspicion = 100,
                            MinAverageScore = 65,
                            MinTurnsToComplete = 5,
                            NpcId = 1,
                            Stage = "Stage 12",
                            StartSuspicion = 10,
                            SyntaxPuzzlesJson = "[]",
                            Title = "Dịch vụ Khách hàng",
                            WritingObjective = "Sử dụng câu bị động (Passive Voice) và lời xin lỗi lịch sự (I apologize for...).",
                            XpReward = 260
                        },
                        new
                        {
                            Id = 13,
                            ApprovalStatus = 0,
                            CefrLevel = 4,
                            Description = "*The meeting room is set, and your coworker looks skeptical.* \"Obviously, changing our workflow management software will cause too much disruption. Why should we support this change?\" *The team leads turn to look at you.*",
                            Difficulty = "Advanced",
                            Domain = 1,
                            Goal = "Trình bày lập luận thuyết phục để đồng nghiệp đồng ý với phương án quản lý mới.",
                            GrammarTarget = "Sử dụng câu điều kiện loại 3 (If we had...) và từ nối phản lập (However, On the other hand).",
                            ImageUrl = "/scenario_boardroom.png",
                            InitialChoices = new List<string> { "Hello!", "Can you help me?", "I have a question.", "Let's start." },
                            Locked = true,
                            MaxSuspicion = 100,
                            MinAverageScore = 78,
                            MinTurnsToComplete = 7,
                            NpcId = 3,
                            Stage = "Stage 13",
                            StartSuspicion = 10,
                            SyntaxPuzzlesJson = "[]",
                            Title = "Thuyết phục Đồng nghiệp",
                            WritingObjective = "Sử dụng câu điều kiện loại 3 (If we had...) và từ nối phản lập (However, On the other hand).",
                            XpReward = 480
                        },
                        new
                        {
                            Id = 14,
                            ApprovalStatus = 0,
                            CefrLevel = 2,
                            Description = "*You're at the annual business mixer. An investor approaches you.* \"I heard your team is working on a new data security solution. Sounds ambitious. Tell me, what makes your team unique?\"",
                            Difficulty = "Intermediate",
                            Domain = 2,
                            Goal = "Tạo ấn tượng tốt với các chuyên gia qua cuộc trò chuyện ngắn ngủi.",
                            GrammarTarget = "Sử dụng thì hiện tại hoàn thành (Present Perfect) để mô tả thành tích và câu hỏi Follow-up questions.",
                            ImageUrl = "/scenario_coffee.png",
                            InitialChoices = new List<string> { "Hello!", "Can you help me?", "I have a question.", "Let's start." },
                            Locked = true,
                            MaxSuspicion = 100,
                            MinAverageScore = 68,
                            MinTurnsToComplete = 5,
                            NpcId = 2,
                            Stage = "Stage 14",
                            StartSuspicion = 10,
                            SyntaxPuzzlesJson = "[]",
                            Title = "Sự kiện Kết nối",
                            WritingObjective = "Sử dụng thì hiện tại hoàn thành (Present Perfect) để mô tả thành tích và câu hỏi Follow-up questions.",
                            XpReward = 320
                        },
                        new
                        {
                            Id = 15,
                            ApprovalStatus = 0,
                            CefrLevel = 4,
                            Description = "*After the keynote on cloud computing, the speaker opens the floor. You raise your hand.* \"Professor Chen, your research mentions cost efficiency. How do you respond to concerns regarding data privacy?\"",
                            Difficulty = "Advanced",
                            Domain = 1,
                            Goal = "Đặt câu hỏi học thuật và nhận xét về bài thuyết trình.",
                            GrammarTarget = "Sử dụng câu gián tiếp (Indirect Questions) và từ nối học thuật (While, Whereas).",
                            ImageUrl = "/scenario_classroom.png",
                            InitialChoices = new List<string> { "Hello!", "Can you help me?", "I have a question.", "Let's start." },
                            Locked = true,
                            MaxSuspicion = 100,
                            MinAverageScore = 72,
                            MinTurnsToComplete = 6,
                            NpcId = 2,
                            Stage = "Stage 15",
                            StartSuspicion = 10,
                            SyntaxPuzzlesJson = "[]",
                            Title = "Hỏi & Đáp Hội nghị",
                            WritingObjective = "Sử dụng câu gián tiếp (Indirect Questions) và từ nối học thuật (While, Whereas).",
                            XpReward = 380
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Npc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NpcEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Npcs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Một nhân viên pha chế thân thiện trong quán cà phê ấm cúng.",
                            Name = "Barista",
                            NpcEmoji = "☕",
                            Personality = "Lịch sự, chu đáo, giúp khách hàng chọn lựa đồ uống phù hợp.",
                            Role = "Pha chế"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Giám sát viên quản lý tiến độ và phân chia công việc.",
                            Name = "Supervisor",
                            NpcEmoji = "📋",
                            Personality = "Chuyên nghiệp, chú trọng chi tiết, yêu cầu độ chính xác trong giao tiếp.",
                            Role = "Giám sát viên"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Giám đốc điều hành sắc sảo và giàu kinh nghiệm.",
                            Name = "Director",
                            NpcEmoji = "👤",
                            Personality = "Sắc sảo, thực tế, đòi hỏi các báo cáo rõ ràng và giải pháp thiết thực.",
                            Role = "Giám đốc"
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("PaymentUrl")
                        .HasColumnType("text");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DiscountPriceXp")
                        .HasColumnType("integer");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriceXp")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ShopItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tiết lộ các gợi ý từ vựng và câu trả lời hữu ích trong hội thoại.",
                            DiscountPriceXp = 160,
                            Emoji = "💡",
                            Name = "Gợi ý thông thái",
                            PriceXp = 200,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Giảm bớt sự bối rối hoặc mức nghi ngờ từ đối phương.",
                            DiscountPriceXp = 0,
                            Emoji = "📕",
                            Name = "Từ điển ngoại giao",
                            PriceXp = 500,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Vật phẩm lưu niệm vàng danh giá dành cho người học xuất sắc.",
                            DiscountPriceXp = 0,
                            Emoji = "🏅",
                            Name = "Huy hiệu Vàng",
                            PriceXp = 1000,
                            Type = 3
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Features")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quyền truy cập miễn phí giới hạn vào các kịch bản bắt đầu",
                            DurationDays = 0,
                            Features = new List<string> { "Kịch bản khởi đầu", "Năng lượng mỗi ngày" },
                            Name = "Gói Miễn Phí",
                            Price = 0m,
                            Tier = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mở khóa toàn bộ tính năng và kịch bản cao cấp",
                            DurationDays = 30,
                            Features = new List<string> { "Toàn bộ Kịch bản", "Năng lượng vô cực", "Phản hồi AI nâng cao" },
                            Name = "Premium VIP",
                            Price = 199000m,
                            Tier = 1
                        });
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Energy")
                        .HasColumnType("integer");

                    b.Property<string>("EnglishLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastEnergyRechargedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxEnergy")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("StreakCount")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XpBalance")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "BadgeId")
                        .IsUnique();

                    b.ToTable("UserBadges", (string)null);
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique();

                    b.ToTable("UserInventories", (string)null);
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CompletionToken")
                        .HasColumnType("text");

                    b.Property<int>("CurrentSuspicion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MissionId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TurnCount")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("UserId", "MissionId")
                        .IsUnique();

                    b.ToTable("UserProgresses", (string)null);
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.WritingSkillSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiRewriteSuggestion")
                        .HasColumnType("text");

                    b.Property<decimal>("AverageScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("BestSentence")
                        .HasColumnType("text");

                    b.Property<int>("ClarityScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GrammarScore")
                        .HasColumnType("integer");

                    b.Property<int>("MissionId")
                        .HasColumnType("integer");

                    b.Property<int>("NaturalnessScore")
                        .HasColumnType("integer");

                    b.Property<int>("StructureScore")
                        .HasColumnType("integer");

                    b.Property<int>("ToneScore")
                        .HasColumnType("integer");

                    b.Property<int>("TurnsCount")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("VocabularyScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CompletedAt");

                    b.ToTable("WritingSkillSnapshots", (string)null);
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Correction", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.Dialogue", "Dialogue")
                        .WithMany()
                        .HasForeignKey("DialogueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dialogue");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Dialogue", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheUnraveller.Core.Entities.Npc", "Npc")
                        .WithMany()
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheUnraveller.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Npc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Mission", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TheUnraveller.Core.Entities.Npc", "Npc")
                        .WithMany()
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.Payment", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserBadge", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheUnraveller.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserInventory", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.ShopItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheUnraveller.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.UserProgress", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheUnraveller.Core.Entities.User", "User")
                        .WithMany("Progresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.WritingSkillSnapshot", b =>
                {
                    b.HasOne("TheUnraveller.Core.Entities.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheUnraveller.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TheUnraveller.Core.Entities.User", b =>
                {
                    b.Navigation("Progresses");
                });
#pragma warning restore 612, 618
        }
    }
}
