-- =====================================================
-- Writing Coach Schema Migration for The Unraveller
-- Database: PostgreSQL (Supabase)
-- Created: 2026-06-18
-- =====================================================
-- This script adds the Writing Coach feature schema including:
-- - WritingSkillSnapshots (user progress aggregations)
-- - Corrections (per-turn grammar/vocabulary/tone corrections)
-- - Badges & UserBadges (gamification)
-- - Indexes for performance
-- =====================================================

-- Run this script on your production database after backing up!
-- Rollback script available: rollback_writing_coach_schema.sql

BEGIN;

-- =====================================================
-- 1. WritingSkillSnapshots Table
-- =====================================================
CREATE TABLE IF NOT EXISTS "WritingSkillSnapshots" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "MissionId" integer NOT NULL,
    "CompletedAt" timestamp with time zone NOT NULL,
    "AverageScore" decimal(5,2) NOT NULL,
    "GrammarScore" integer NOT NULL,
    "VocabularyScore" integer NOT NULL,
    "ToneScore" integer NOT NULL,
    "NaturalnessScore" integer NOT NULL,
    "ClarityScore" integer NOT NULL,
    "StructureScore" integer NOT NULL,
    "TurnsCount" integer NOT NULL,
    "BestSentence" text NULL,
    "AiRewriteSuggestion" text NULL,
    CONSTRAINT "FK_WritingSkillSnapshots_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WritingSkillSnapshots_Missions_MissionId" FOREIGN KEY ("MissionId") REFERENCES "Missions" ("Id") ON DELETE CASCADE
);

-- Indexes for WritingSkillSnapshots
CREATE INDEX IF NOT EXISTS "IX_WritingSkillSnapshots_UserId" ON "WritingSkillSnapshots"("UserId");
CREATE INDEX IF NOT EXISTS "IX_WritingSkillSnapshots_UserId_CompletedAt" ON "WritingSkillSnapshots"("UserId", "CompletedAt" DESC);
CREATE INDEX IF NOT EXISTS "IX_WritingSkillSnapshots_MissionId" ON "WritingSkillSnapshots"("MissionId");

-- =====================================================
-- 2. Corrections Table
-- =====================================================
CREATE TABLE IF NOT EXISTS "Corrections" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DialogueId" integer NOT NULL,
    "Axis" integer NOT NULL, -- enum: 0=Grammar, 1=Vocabulary, 2=Tone, 3=Naturalness, 4=Clarity, 5=Structure
    "OriginalText" text NOT NULL,
    "CorrectedText" text NOT NULL,
    "Explanation" text NOT NULL,
    CONSTRAINT "FK_Corrections_Dialogues_DialogueId" FOREIGN KEY ("DialogueId") REFERENCES "Dialogues" ("Id") ON DELETE CASCADE
);

-- Indexes for Corrections
CREATE INDEX IF NOT EXISTS "IX_Corrections_DialogueId" ON "Corrections"("DialogueId");

-- =====================================================
-- 3. Badges Table (seed data included)
-- =====================================================
CREATE TABLE IF NOT EXISTS "Badges" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(100) NOT NULL,
    "Description" varchar(500) NULL,
    "Icon" varchar(50) NULL,
    "CriteriaType" text NULL,
    "RequiredCount" integer NULL,
    "SkillAxis" integer NULL,
    "MinAverageScore" integer NULL
);

-- Seed Badge Definitions
INSERT INTO "Badges" ("Id", "Name", "Description", "Icon", "CriteriaType", "RequiredCount", "SkillAxis", "MinAverageScore") VALUES
(1, 'First Steps', 'Complete your first mission', '👣', 'FirstCompletion', NULL, NULL, NULL),
(2, 'Skillful', 'Achieve an average score of 70 or higher on any mission', '🎯', 'MinAverageScore', NULL, NULL, 70),
(3, 'Perfectionist', 'Achieve an average score of 90 or higher on any mission', '💎', 'MinAverageScore', NULL, NULL, 90),
(4, 'Streak Master', 'Complete 5 missions in a row without failing', '🔥', 'Streak', 5, NULL, NULL),
(5, 'Writing Coach', 'Earn 1000 total XP', '🏆', 'TotalXp', 1000, NULL, NULL),
(6, 'Polished', 'Receive all scores above 80 in a single turn', '✨', 'PerfectTurn', NULL, NULL, NULL),
(7, 'Linguist', 'Complete missions in all three domains: Professional, Academic, Social', '🌍', 'DomainDiversity', NULL, NULL, NULL),
(8, 'Lifetime Learner', 'Complete 10 missions total', '📚', 'TotalCompletions', 10, NULL, NULL)
ON CONFLICT ("Id") DO NOTHING;

-- =====================================================
-- 4. UserBadges Table (junction table)
-- =====================================================
CREATE TABLE IF NOT EXISTS "UserBadges" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" integer NOT NULL,
    "BadgeId" integer NOT NULL,
    "EarnedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_UserBadges_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserBadges_Badges_BadgeId" FOREIGN KEY ("BadgeId") REFERENCES "Badges" ("Id") ON DELETE CASCADE
);

-- Unique constraint to prevent duplicate badge awards per user
CREATE UNIQUE INDEX IF NOT EXISTS "IX_UserBadges_UserId_BadgeId" ON "UserBadges"("UserId", "BadgeId");
CREATE INDEX IF NOT EXISTS "IX_UserBadges_UserId" ON "UserBadges"("UserId");

-- =====================================================
-- 5. Ensure Dialogues table has score columns
-- (May already exist from earlier migration)
-- =====================================================
ALTER TABLE "Dialogues" ADD COLUMN IF NOT EXISTS "GrammarScore" integer;
ALTER TABLE "Dialogues" ADD COLUMN IF NOT EXISTS "VocabularyScore" integer;
ALTER TABLE "Dialogues" ADD COLUMN IF NOT EXISTS "ToneScore" integer;
ALTER TABLE "Dialogues" ADD COLUMN IF NOT EXISTS "NaturalnessScore" integer;
ALTER TABLE "Dialogues" ADD COLUMN IF NOT EXISTS "ClarityScore" integer;
ALTER TABLE "Dialogues" ADD COLUMN IF NOT EXISTS "StructureScore" integer;

-- =====================================================
-- 6. Additional Performance Indexes
-- =====================================================
-- These complement existing indexes from AddPerformanceIndexes migration

-- Index for UserProgresses by Status (already exists, verify)
-- CREATE INDEX IF NOT EXISTS "IX_UserProgresses_UserId_Status" ON "UserProgresses"("UserId", "Status");

-- Index for Missions by ApprovalStatus and Domain (already exists, verify)
-- CREATE INDEX IF NOT EXISTS "IX_Missions_ApprovalStatus_Domain" ON "Missions"("ApprovalStatus", "Domain");

COMMIT;

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================
-- After running this migration, verify with:
--
-- \d "WritingSkillSnapshots"
-- \d "Corrections"
-- \d "Badges"
-- \d "UserBadges"
--
-- SELECT COUNT(*) FROM "WritingSkillSnapshots";
-- SELECT COUNT(*) FROM "Corrections";
-- SELECT COUNT(*) FROM "Badges"; -- should return 8
-- SELECT COUNT(*) FROM "UserBadges";
--
-- Verify indexes:
-- \di "IX_WritingSkillSnapshots_UserId"
-- \di "IX_Corrections_DialogueId"
-- \di "IX_UserBadges_UserId_BadgeId"
