using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TheUnraveller.Infrastructure.Data.Migrations;

public partial class AddBadgeSystem : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // Create Badges table
        migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS ""Badges"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""Name"" varchar(100) NOT NULL,
                ""Description"" varchar(500) NULL,
                ""Icon"" varchar(50) NULL,
                ""CriteriaType"" text NULL,
                ""RequiredCount"" integer NULL,
                ""SkillAxis"" integer NULL,
                ""MinAverageScore"" integer NULL
            );
        ");

        // Create UserBadges table
        migrationBuilder.Sql(@"
            CREATE TABLE IF NOT EXISTS ""UserBadges"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""UserId"" integer NOT NULL,
                ""BadgeId"" integer NOT NULL,
                ""EarnedAt"" timestamp with time zone NOT NULL DEFAULT NOW()
            );
        ");

        // Create indexes
        migrationBuilder.Sql(@"
            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_UserBadges_UserId_BadgeId"" ON ""UserBadges""(""UserId"", ""BadgeId"");
            CREATE INDEX IF NOT EXISTS ""IX_UserBadges_UserId"" ON ""UserBadges""(""UserId"");
        ");

        // Seed initial badges
        migrationBuilder.Sql(@"
            INSERT INTO ""Badges"" (""Id"", ""Name"", ""Description"", ""Icon"", ""CriteriaType"", ""RequiredCount"", ""SkillAxis"", ""MinAverageScore"") VALUES
            (1, 'First Steps', 'Complete your first mission', '👣', 'FirstCompletion', NULL, NULL, NULL),
            (2, 'Skillful', 'Achieve an average score of 70 or higher on any mission', '🎯', 'MinAverageScore', NULL, NULL, 70),
            (3, 'Perfectionist', 'Achieve an average score of 90 or higher on any mission', '💎', 'MinAverageScore', NULL, NULL, 90),
            (4, 'Streak Master', 'Complete 5 missions in a row without failing', '🔥', 'Streak', 5, NULL, NULL),
            (5, 'Writing Coach', 'Earn 1000 total XP', '🏆', 'TotalXp', 1000, NULL, NULL),
            (6, 'Polished', 'Receive all scores above 80 in a single turn', '✨', 'PerfectTurn', NULL, NULL, NULL),
            (7, 'Linguist', 'Complete missions in all three domains: Professional, Academic, Social', '🌍', 'DomainDiversity', NULL, NULL, NULL),
            (8, 'Lifetime Learner', 'Complete 10 missions total', '📚', 'TotalCompletions', 10, NULL, NULL)
            ON CONFLICT (""Id"") DO NOTHING;
        ");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"
            DROP TABLE IF EXISTS ""UserBadges"" CASCADE;
            DROP TABLE IF EXISTS ""Badges"" CASCADE;
        ");
    }
}
